FROM node:20-slim
RUN apt-get update && apt-get install -y openssl
WORKDIR /workspace
COPY package*.json tsconfig.base.json ./
COPY apps/ui/package.json apps/ui/tsconfig.json /workspace/apps/ui/
COPY packages/core /workspace/packages/core/
RUN npm install && npm run build --workspace packages/core
CMD ["npm", "--workspace", "apps/ui", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
